"""
A Coffee Roastery Subscription Manager — FastAPI backend generated by Startup Agent.

Serves the JSON API and (in production) the built frontend from /frontend/dist.
"""
import os
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from .db import create_item, delete_item, list_items, update_item
from .schemas import ItemCreate, ItemUpdate

app = FastAPI(title="A Coffee Roastery Subscription Manager", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health():
    return {"status": "ok", "service": "A Coffee Roastery Subscription Manager"}


@app.get("/api/items")
def get_items():
    return list_items()


@app.post("/api/items", status_code=201)
def post_item(payload: ItemCreate):
    return create_item(payload.title.strip())


@app.patch("/api/items/{item_id}")
def patch_item(item_id: int, payload: ItemUpdate):
    item = update_item(item_id, title=payload.title.strip() if payload.title else None, completed=payload.completed)
    if item is None:
        raise HTTPException(status_code=404, detail="item not found")
    return item


@app.delete("/api/items/{item_id}", status_code=204)
def delete_item_route(item_id: int):
    if not delete_item(item_id):
        raise HTTPException(status_code=404, detail="item not found")
    return None


# ---- serve the built frontend in production ----
_dist = Path(__file__).parent.parent.parent / "frontend" / "dist"
if _dist.exists() and (_dist / "index.html").exists():
    app.mount("/assets", StaticFiles(directory=_dist / "assets"), name="assets")

    @app.get("/{path:path}")
    def spa(path: str):
        if path.startswith("api/"):
            raise HTTPException(status_code=404)
        return FileResponse(_dist / "index.html")
